ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name='index'),
    path('categoria/<int:categoria_id>',views.productos_por_categoria,name='categoria'),
    path('marca/<int:marca_id>',views.productos_por_marca,name='marca'),
    path('buscar',views.productos_por_nombre,name='buscar'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('carrito/add/<int:producto_id>',views.agregar_carrito,name='carritoadd'),
    path('carrito/del/<int:producto_id>',views.eliminar_carrito,name='carritodel'),
    path('carrito/clear',views.limpiar_carrito,name='carritoclear'),
    path('usuario/add',views.crear_usuario,name='usuarioadd'),
    path('cuenta',views.cuenta_usuario,name='cuenta'),
    path('login',views.login_usuario,name='usuariologin'),
    path('logout',views.logout_usuario,name='usuariologout'),
    path('cliente/update',views.actualizar_cliente,name='clienteupdate'),
    path('pedido',views.confirmar_pedido,name='pedido'),
    path('registrarpedido',views.registrar_pedido,name='registrarpedido'),
    path('pedido/pagado',views.pedido_pagado,name='pedidopagado')
]

ecommerce/web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'tbl_categoria'
        
    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'tbl_marca'
        
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    marca = models.ForeignKey(Marca,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=254)
    descripcion = models.TextField(null=True)
    precio = models.DecimalField(max_digits=5,decimal_places=2)
    imagen = models.ImageField(upload_to='productos',blank=True)
    
    class Meta:
        db_table = 'tbl_producto'
        
    def __str__(self):
        return self.nombre
    
from django.contrib.auth.models import User

class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    dni = models.CharField(max_length=8)
    telefono = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()
    
    class Meta:
        db_table = 'tbl_cliente'
    
    def __str__(self):
        return self.dni
    
class Pedido(models.Model):
    ESTADO_CHOICES = (
        ('S','SOLICITADO'),
        ('P','PAGADO')
    )
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=5,decimal_places=2,default=0)
    direccion_envio = models.TextField(null=True)
    estado = models.CharField(max_length=1,default='S',choices=ESTADO_CHOICES)
    
    
    class Meta:
        db_table = 'tbl_pedido'
        
    def __str__(self):
        return self.nro_pedido
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    precio = models.DecimalField(max_digits=5,decimal_places=2)
    subtotal = models.DecimalField(max_digits=5,decimal_places=2)
    
    class Meta:
        db_table = 'tbl_pedido_detalle'
        
    def __str__(self):
        return self.producto.nombre
    

ecommerce/web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">Carrito</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Cart</li>
    </ul>
    <div class="page-styling">
        <div class="woocommerce prod-litems section-list">
            {% for key,value in request.session.cart.items %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="product.html" class="prod-li-img">
                        <img src="{{value.imagen}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{value.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{value.nombre}}</a></h3>
                        </div><!--
        No Space
        --><div class="prod-li-prices">
                        <div class="prod-li-price-wrap">
                            <p>Price</p>
                            <p class="prod-li-price">${{value.precio}}</p>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{value.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{value.subtotal}}</p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p class="prod-li-add">
                                <a href="{% url 'web:carritodel' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i></a>
                            </p>
                        </div>
                    </div><!--
    No Space
    --></div>

                </div>
            </article>
            {% endfor %}
        </div>
        <div class="cart-actions">
            <div class="coupon">
                <input type="text" placeholder="Coupon code">
                <input type="submit" class="button" value="Apply">
            </div>
            <div class="cart-collaterals">
                <a href="{% url 'web:carritoclear' %}" class="checkout-button button">LIMPIAR CARRITO</a> - 
                <a href="{% url 'web:pedido' %}" class="checkout-button button">REGISTRAR PEDIDO</a>
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{request.session.total}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/web/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">BIENVENIDO {{user.username}}</h1>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos del Cliente</h2>
                    <form method="post" class="login" action="{% url 'web:clienteupdate' %}">
                        {% csrf_token %}
                        {{form}}
                        <p class ="auth-submit">
                            <input type="submit" value="Actualizar Datos"/>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
</div>
{% endblock %}

ecommerce/web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">

    <div class="section-top">

        <h1 class="maincont-ttl">Shop</h1>
        <ul class="b-crumbs">
            <li><a href="index.html">Home</a></li>
            <li>Catalog - Gallery</li>
        </ul>
        <div class="section-top-sort">
            <div class="section-view">
                <p>View</p>
                <div class="dropdown-wrap">
                    <p class="dropdown-title section-view-ttl">Gallery</p>
                    <ul class="dropdown-list">
                        <li>
                            <a href="catalog-list.html">List</a>
                        </li>
                        <li class="active">
                            <a href="catalog-gallery.html">Gallery</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="section-sort">
                <p>Sort</p>
                <div class="dropdown-wrap">
                    <p class="dropdown-title section-sort-ttl">Newness</p>
                    <ul class="dropdown-list">
                        <li>
                            <a href="#">Popularity</a>
                        </li>
                        <li>
                            <a href="#">Average rating</a>
                        </li>
                        <li class="active">
                            <a href="#">Newness</a>
                        </li>
                        <li>
                            <a href="#">Price: low to high</a>
                        </li>
                        <li>
                            <a href="#">Price: high to low</a>
                        </li>
                    </ul>
                </div>
            </div>
            <form method="post" class="products-per-page">
                <p>Per Page</p>
                <select>
                    <option value="12" selected="selected">12</option>
                    <option value="24">24</option>
                    <option value="48">48</option>
                    <option value="-1">All</option>
                </select>
            </form>
        </div>
    </div>

    <!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
    <div class="section-wrap-withsb">
        <aside class="blog-sb-widgets section-sb" id="section-sb">
            <div class="theiaStickySidebar">
                <p class="section-filter-toggle filter_hidden">
                    <a href="#" id="section-filter-toggle-btn">Show Filter</a>
                </p>
                <div class="section-filter">
                    <div class="section-filter">
                        <div class="blog-sb-widget multishopcategories_widget">
                            <h3 class="widgettitle">Categorias</h3>
                            <div class="section-sb-current">
                                <ul class="section-sb-list">
                                    {% for categoria in categorias %}
                                    <li>
                                        <a href="{% url 'web:categoria' categoria.id %}">
                                            <span class="section-sb-label">{{categoria.nombre}} 
                                        <span class="count">{{categoria.producto_set.all.count}}</span></span></a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="blog-sb-widget multishopbrands_widget">
                            <h3 class="widgettitle">Marcas</h3>
                            <ul class="brands-list-sb">
                                {% for marca in marcas %}
                                <li>
                                    <a href="{% url 'web:marca' marca.id %}">{{marca.nombre}} 
                                        <span class="count">{{marca.producto_set.all.count}}</span></a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </aside>        <div class="section-list-withsb" id="section-list-withsb">
        <div class="theiaStickySidebar">
            <div class="row prod-items prod-items-2">
                {% for producto in productos %}
                <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                    <div class="sectgl prod-i">
                        <div class="prod-i-top">
                            <a class="prod-i-img" href="{% url 'web:producto' producto.id %}">
                                <img src="{{producto.imagen.url}}" alt="">
                            </a>
                        </div>
                        <div class="prod-i-bot">
                            <div class="prod-i-info">
                                <p class="prod-i-price">${{producto.precio}}</p>
                                <p class="prod-i-categ"><a href="catalog-gallery.html">{{producto.marca.nombre}}</a></p>
                            </div>
                            <h3 class="prod-i-ttl"><a href="{% url 'web:producto' producto.id %}">{{producto.nombre}}</a></h3>
                        </div>
                    </div>
                </article>
                {% endfor %}        
            </div>
            <ul class="page-numbers">
                <li><span class="page-numbers current">1</span></li>
                <li><a class="page-numbers" href="#">2</a></li>
                <li><a class="page-numbers" href="#">3</a></li>
                <li><a class="page-numbers" href="#">4</a></li>
                <li><a class="next page-numbers" href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
        </div><!-- .theiaStickySidebar -->
    </div><!-- .section-list-withsb -->
    </div><!-- .section-wrap-withsb -->

</div>
{% endblock %}

ecommerce/web/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>TIENDA G22</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}">
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}">

</head>
<body>
<div id="page" class="site">
    {% include 'includes/navBar.html' %}
    {% include 'includes/header.html' %}
    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                {%block content %}
                {% endblock %}
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->
    {% include 'includes/footer.html' %}
    {% include 'includes/modals.html' %}
</div><!-- #page -->

<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

ecommerce/web/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">Registration / Login</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Registration & Login</li>
    </ul>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Login</h2>
                    <form method="post" class="login" action="{% url 'web:usuariologin' %}">
                        {% csrf_token %}
                        <input type="hidden" name="destino" value="{{destino}}"/>
                        <p>
                            <label for="username">E-mail <span class="required">*</span></label>
                            <input type="text" id="username" name="usuario">
                        </p>
                        <p>
                            <label for="password">Password <span class="required">*</span></label>
                            <input type="password" id="password" name="password">
                        </p>
                        <p class="auth-submit">
                            <input type="submit" value="Login">
                            <input type="checkbox" id="rememberme" value="forever">
                            <label for="rememberme">Remember me</label>
                        </p>
                        <p class="auth-lost_password">
                            <label for="alert-danger">{{mensaje_error}}</label>
                        </p>
                    </form>
                </div>
                <div class="auth-col">
                    <h2>Registrarse</h2>
                    <form method="post" class="register" action="{% url 'web:usuarioadd' %}">
                        {% csrf_token %}
                        <input type="hidden" name="destino" value="{{destino}}"/>
                        <p>
                            <label for="reg_email">Email <span class="required">*</span></label>
                            <input type="text" id="reg_email" name="usuario">
                        </p>
                        <p>
                            <label for="reg_password">Password <span class="required">*</span></label>
                            <input type="password" id="reg_password" name="password">
                        </p>
                        <p class="auth-submit">
                            <input type="submit" value="Register">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
</div>
{% endblock %}

ecommerce/web/templates/pago.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">SU PEDIDO FUE REGISTRADO</h1>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos de Pedido</h2>
                    <p>Nro Pedido : {{pedido.nro_pedido}}</p>
                    <p>Fecha : {{pedido.fecha_registro}}</p>
                    <p>Cliente : {{pedido.cliente.usuario.first_name}} {{pedido.cliente.usuario.last_name}}</p>
                </div>
                <div class="auth-col">
                    <p>MONTO TOTAL A PAGAR : {{pedido.monto_total}}</p>
                    {{paypal_form.render}}
                </div>
            </div>
        </div>
        <div class="page-styling">
            <div class="woocommerce prod-litems section-list">
                {% for detalle in pedido.pedidodetalle_set.all %}
                <article class="prod-li sectls">
                    <div class="prod-li-inner">
                        <a href="product.html" class="prod-li-img">
                            <img src="{{detalle.producto.imagen.url}}" alt="">
                        </a>
                        <div class="prod-li-cont">
                            <div class="prod-li-ttl-wrap">
                                <p>
                                    <a href="#">{{detalle.producto.categoria}}</a>
                                </p>
                                <h3><a href="product.html">{{detalle.producto.nombre}}</a></h3>
                            </div><!--
            No Space
            --><div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Price</p>
                                <p class="prod-li-price">${{detalle.precio}}</p>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    {{detalle.cantidad}}
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Total</p>
                                <p class="prod-li-total">${{detalle.subtotal}}</p>
                            </div>
                        </div><!--
        No Space
        --></div>
    
                    </div>
                </article>
                {% endfor %}
            </div>
    </article>
</div>
{% endblock %}

ecommerce/web/templates/pedido.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">CONFIRMACIÓN DE PEDIDO</h1>
    <form action="{% url 'web:registrarpedido' %}" method="post">
        {% csrf_token %}
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos del Cliente</h2>
                    <p>
                        <label for="nombre">Nombres</label>
                        {{form.nombre}}
                    </p>
                    <p>
                        <label for="nombre">Apellidos</label>
                        {{form.apellidos}}
                    </p>
                    <p>
                        <label for="nombre">Email</label>
                        {{form.email}}
                    </p>
                </div>
                <div class="auth-col">
                    <h2>Datos de Envio</h2>
                    <p>
                        <label for="nombre">Telefono</label>
                        {{form.telefono}}
                    </p>
                    <p>
                        <label for="nombre">Dirección</label>
                        {{form.direccion}}
                    </p> 
                </div>
            </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Detalle de Pedido</h2>
                    <div class="woocommerce prod-litems section-list">
                        {% for key,value in request.session.cart.items %}
                        <article class="prod-li sectls">
                            <div class="prod-li-inner">
                                <a href="product.html" class="prod-li-img">
                                    <img src="{{value.imagen}}" alt="">
                                </a>
                                    <div class="prod-li-cont">
                                        <div class="prod-li-ttl-wrap">
                                            <p>
                                                <a href="#">{{value.categoria}}</a>
                                            </p>
                                            <h3><a href="product.html">{{value.nombre}}</a></h3>
                                        </div>
                                        <div class="prod-li-prices">
                                            <div class="prod-li-price-wrap">
                                                <p>Price</p>
                                                <p class="prod-li-price">${{value.precio}}</p>
                                            </div>
                                            <div class="prod-li-qnt-wrap">
                                                <p class="qnt-wrap prod-li-qnt">
                                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                                    <input type="text" value="{{value.cantidad}}">
                                                    <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                                </p>
                                            </div>
                                            <div class="prod-li-total-wrap">
                                                <p>Total</p>
                                                <p class="prod-li-total">${{value.subtotal}}</p>
                                            </div>
                                            <div class="prod-li-total-wrap">
                                                <p class="prod-li-add">
                                                    <a href="{% url 'web:carritodel' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i></a>
                                                </p>
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </article>
                        {% endfor %}
                    </div>
                </div>
                <div class="auth-col">
                    <div class="order-total">
                        <p class="cart-totals-ttl">Total</p>
                        <p class="cart-totals-val">${{request.session.total}}</p>
                    </div>
                    <input type="submit" class="checkout-button button" value="CONFIRMAR PEDIDO"/>
                </div>
            </div>
        </div>
    </article>
    </form>
</div>
{% endblock %}

ecommerce/web/templates/pedidopagado.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">SU PEDIDO FUE PAGADO CON EXITO</h1>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos de Pedido</h2>
                    <p>Nro Pedido : {{pedido.nro_pedido}}</p>
                    <p>Fecha : {{pedido.fecha_registro}}</p>
                    <p>Cliente : {{pedido.cliente.usuario.first_name}} {{pedido.cliente.usuario.last_name}}</p>
                </div>
            </div>
        </div>
    </article>
</div>
{% endblock %}

ecommerce/web/templates/producto.html
{% extends 'layout.html'%}
{%block content %}
<div class="cont maincont">
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li><a href="catalog-gallery.html">Catalog</a></li>
        <li>Product</li>
    </ul>
    <article>
        <div class="prod">
            <div class="prod-slider-wrap prod-slider-shown">
                <div class="flexslider prod-slider" id="prod-slider">
                    <ul class="slides">
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/810x722">
                                <img src="{{producto.imagen.url}}" alt="">
                            </a>
                        </li>
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/800x800">
                                <img src="{{producto.imagen.url}}" alt="">
                            </a>
                        </li>
                    </ul>
                    <div class="prod-slider-count"><p><span class="count-cur">1</span> / <span class="count-all">2</span></p><p class="hover-label prod-slider-zoom"><i class="icon ion-search"></i><span>Zoom In</span></p></div>
                </div>
                <div class="flexslider prod-thumbs" id="prod-thumbs">
                    <ul class="slides">
                        <li>
                            <img src="{{producto.imagen.url}}" alt="">
                        </li>
                        <li>
                            <img src="{{producto.imagen.url}}" alt="">
                        </li>
                    </ul>
                </div>
            </div>

            <div class="prod-cont">
            <form action="{% url 'web:carritoadd' producto.id %}" method="post">
                {% csrf_token %}
                <div class="prod-rating-wrap">
                    <p data-rating="4" class="prod-rating">
                        <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                    </p>
                    <p class="prod-rating-count">7</p>
                </div>
                <p class="prod-categs"><a href="#">{{producto.categoria.nombre}}</a>, <a href="#">{{producto.marca.nombre}}</a></p>
                <h1>{{producto.nombre}}</h1>
                <div class="variations_form cart">
                    <p>
                        {{producto.descripcion}}
                    </p>
                    <div class="prod-add">

                        <button type="submit" class="button">
                            <i class="icon ion-android-cart"></i> Agregar al Carrito
                        </button>
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" name="cantidad" value="1">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                        <div class="prod-li-favorites">
                            <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                        </div>
                        <p class="prod-li-compare">
                            <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                        </p>
                    </div>
                </div>
            </form>
            </div>
            <p class="prod-badge">
                <span class="badge-1">TOP SELLER</span>
            </p>
        </div>
    </article>
</div>
{% endblock %}