ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('web.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name='index'),
    path('categoria/<int:categoria_id>',views.productos_por_categoria,name='categoria'),
    path('marca/<int:marca_id>',views.productos_por_marca,name='marca'),
    path('buscar',views.productos_por_nombre,name='buscar'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('carrito/add/<int:producto_id>',views.agregar_carrito,name='carritoadd'),
    path('carrito/del/<int:producto_id>',views.eliminar_carrito,name='carritodel'),
    path('carrito/clear',views.limpiar_carrito,name='carritoclear'),
    path('usuario/add',views.crear_usuario,name='usuarioadd'),
    path('cuenta',views.cuenta_usuario,name='cuenta'),
    path('login',views.login_usuario,name='usuariologin'),
    path('logout',views.logout_usuario,name='usuariologout'),
    path('cliente/update',views.actualizar_cliente,name='clienteupdate'),
    path('pedido',views.confirmar_pedido,name='pedido'),
    path('registrarpedido',views.registrar_pedido,name='registrarpedido'),
    path('pedido/pagado',views.pedido_pagado,name='pedidopagado')
]

ecommerce/web/templates/includes/footer.html
<div class="container-fluid blog-sb-widgets page-styling site-footer">
    <div class="row">
        <div class="col-sm-12 col-md-4 widget align-center-tablet f-logo-wrap">
            <a href="index.html" class="f-logo">
                <img src="img/logo.png" alt="">
            </a>
            <p>Modern eCommerce HTML Template</p>
            <button class="btn callback">Contact Us</button>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Company</h3>
            <ul class="menu">
                <li>
                    <a href="index.html">Front Page</a>
                </li>
                <li>
                    <a href="about.html">About Us</a>
                </li>
                <li>
                    <a href="contacts.html">Contacts</a>
                </li>
                <li>
                    <a href="index.html">Gallery</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Shop</h3>
            <ul class="menu">
                <li>
                    <a href="catalog-list.html">Electricity</a>
                </li>
                <li>
                    <a href="catalog-gallery.html">Fasteners</a>
                </li>
                <li>
                    <a href="catalog-gallery-full.html">Lighting</a>
                </li>
                <li>
                    <a href="catalog-gallery.html">Pipes</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Account</h3>
            <ul class="menu">
                <li>
                    <a href="wishlist.html">Wishlist</a>
                </li>
                <li>
                    <a href="compare.html">Compare</a>
                </li>
                <li>
                    <a href="cart.html">Cart</a>
                </li>
                <li>
                    <a href="auth.html">My Account</a>
                </li>
            </ul>
        </div>
        <div class="col-xs-6 col-sm-3 col-md-2 align-center-mobile widget">
            <h3 class="widgettitle">Blog</h3>
            <ul class="menu">
                <li>
                    <a href="blog.html">All Posts</a>
                </li>
                <li>
                    <a href="post.html">News</a>
                </li>
                <li>
                    <a href="post-slider.html">Articles</a>
                </li>
                <li>
                    <a href="blog.html">Reviews</a>
                </li>
            </ul>
        </div>
    </div>
</div>

ecommerce/web/templates/includes/header.html
{%load static %}
<div class="site-header">

    <p class="h-logo">
        <a href="/"><img src="{% static 'img/logo.png' %}" alt="MultiShop"></a>
    </p><!--
No Space
--><div class="h-shop">

    <form method="post" action="{% url 'web:buscar' %}" class="h-search" id="h-search">
        {% csrf_token %}
        <input type="text" name="nombre" placeholder="Search...">
        <button type="submit"><i class="ion-search"></i></button>
    </form>

    <ul class="h-shop-links">
        <li class="h-search-btn" id="h-search-btn"><i class="ion-search"></i></li>
        <li class="h-shop-icon h-profile">
            <a href="{% url 'web:cuenta' %}" title="Mi cuenta">
                <i class="ion-android-person"></i>
            </a>
            <ul class="h-profile-links">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'web:usuariologout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'web:usuariologin' %}">Login / Registration</a></li>
                {% endif %}
                <li><a href="{% url 'web:carrito' %}">Carrito de Compras</a></li>
            </ul>
        </li>

        <li class="h-cart">
            <a class="cart-contents" href="cart.html">
                <p class="h-cart-icon">
                    <i class="ion-android-cart"></i>
                    <span>3</span>
                </p>
                <p class="h-cart-total">$510.00</p>
            </a>
            <div class="widget_shopping_cart">
                <div class="widget_shopping_cart_content">
                    <ul class="cart_list">
                        <li>
                            <a href="#" class="remove">&times;</a>
                            <a href="#">
                                <img src="http://placehold.it/100x67" alt="">
                                Pneumatic Coil Hose
                            </a>
                            <span class="quantity">1 &times; $180.00</span>
                        </li>
                        <li>
                            <a href="#" class="remove">&times;</a>
                            <a href="#">
                                <img src="http://placehold.it/100x89" alt="">
                                Drill Tool Kit
                            </a>
                            <span class="quantity">1 &times; $115.00</span>
                        </li>
                        <li>
                            <a href="#" class="remove">&times;</a>
                            <a href="#">
                                <img src="http://placehold.it/100x89" alt="">
                                Searchlight Portable
                            </a>
                            <span class="quantity">1 &times; $150.00</span>
                        </li>
                    </ul>
                    <p class="total"><b>Subtotal:</b> $510.00</p>
                    <p class="buttons">
                        <a href="cart.html" class="button">View cart</a>
                        <a href="checkout.html" class="button">Checkout</a>
                    </p>
                </div>
            </div>
        </li>

        <li class="h-menu-btn" id="h-menu-btn">
            <i class="ion-navicon"></i> Menu
        </li>
    </ul>
</div>
</div>

ecommerce/web/templates/includes/modals.html
<div class="form-validate modal-form" id="modal-form">
    <form action="#" method="POST" class="form-validate">
        <h4>Contact Us</h4>
        <input type="text" placeholder="Your name" data-required="text" name="name">
        <input type="text" placeholder="Your phone" data-required="text" name="phone">
        <input type="text" placeholder="Your email" data-required="text" data-required-email="email" name="email">
        <input class="btn1" type="submit" value="Send">
    </form>
</div>
<div class="cont maincont quick-view-modal">
    <article>
        <div class="prod">
            <div class="prod-slider-wrap prod-slider-shown">
                <div class="flexslider prod-slider" id="prod-slider">
                    <ul class="slides">
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                        <li>
                            <a data-fancybox-group="prod" class="fancy-img" href="http://placehold.it/1000x1000">
                                <img  src="http://placehold.it/550x550" alt="">
                            </a>
                        </li>
                    </ul>
                    <div class="prod-slider-count"><p><span class="count-cur">1</span> / <span class="count-all">3</span></p><p class="hover-label prod-slider-zoom"><i class="icon ion-search"></i><span>Zoom In</span></p></div>
                </div>
                <div class="flexslider prod-thumbs" id="prod-thumbs">
                    <ul class="slides">
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                        <li>
                            <img src="http://placehold.it/550x550" alt="">
                        </li>
                    </ul>
                </div>
            </div>
            <div class="prod-cont">
                <div class="prod-rating-wrap">
                    <p data-rating="4" class="prod-rating">
                        <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                    </p>
                    <p class="prod-rating-count">7</p>
                </div>
                <p class="prod-categs"><a href="#">Lighting</a>, <a href="#">Tools</a></p>
                <h2>Belt Sanders</h2>
                <p class="prod-price">$25.00</p>
                <p class="stock in-stock">7 in stock</p>
                <p class="prod-excerpt">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget...</p>
                <div class="prod-add">
                    <button type="submit"
                            class="button"><i class="icon ion-android-cart"></i> Add to cart
                    </button>
                    <p class="qnt-wrap prod-li-qnt">
                        <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                        <input type="text" value="1">
                        <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                    </p>
                    <div class="prod-li-favorites">
                        <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                    </div>
                    <p class="prod-li-compare">
                        <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                    </p>
                </div>
            </div>
        </div>
    </article>
</div>

ecommerce/web/templates/includes/navBar.html
<div class="container-fluid page-styling site-header-before">
    <div class="row">
        <div class="col-lg-4">
            <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                <li>
                    <p class="links_list-value">
                        <a href="http://facebook.com" target="_blank" rel="nofollow">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="mailto:email@email.com" target="_blank" rel="nofollow">
                            <i class="fa fa-paper-plane"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://pinterest.com" target="_blank" rel="nofollow">
                            <i class="fa fa-pinterest-p"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://youtube.com" target="_blank" rel="nofollow">
                            <i class="fa fa-youtube-play"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://twitter.com" target="_blank" rel="nofollow">
                            <i class="fa fa-twitter"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://google.com" target="_blank" rel="nofollow">
                            <i class="fa fa-google-plus"></i>
                        </a>
                    </p>
                </li>
                <li>
                    <p class="links_list-value">
                        <a href="http://instagram.com" target="_blank" rel="nofollow">
                            <i class="fa fa-instagram"></i>
                        </a>
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-8">
            <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                <li>
                    <p class="links_list-label">
                        Our Address
                    </p>
                    <p class="links_list-value">
                        <a href="http://maps.google.com" target="_blank" rel="nofollow">15th Street, Miami, USA</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Contact Us
                    </p>
                    <p class="links_list-value">
                        <a href="mailto:support@email.com">Support@Email.com</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Phone
                    </p>
                    <p class="links_list-value">
                        <a href="tel:4785929899">(478)-592-9899</a>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>